### ISSUE TITLE
麴町駅対応

### ISSUE THREAD

**Issue by sakuyuki87** [odpt2018/sapj-opd-trainschedulebot-node#24]
正式名：麴町駅

変換では麹町駅となるので、麹町でも検索できるようにする

※Stationのテーブルに麹町のレコードを追加すればOKだと思います。
重要度:高

**Comment by sakuyuki87** [comment]
Stationのテーブルに正のレコードか、ゆらぎ対応のレコードか判別するフラグが必要

**Comment by Haruyuki-Kobayashi** [comment]
麹町(変換で出てくるほう）の駅名でも結果が返るよう修正
