### ISSUE TITLE
路線行先のテーブル作成

### ISSUE THREAD

**Issue by sakuyuki87** [odpt2018/sapj-opd-trainschedulebot-node#3]
HANA上での路線行先のテーブル作成

**路線情報(API: odpt:Railway)**
項目
1. 路線名(半蔵門線)
2. 路線会社(odpt.Operator:TokyoMetro)
3. 路線ID(odpt.Railway:TokyoMetro.Hanzomon)
4. 到着駅(odpt.Station:TokyoMetro.Hanzomon.Kudanshita)
5. 到着駅番号(odpt:index)

**Comment by sakuyuki87** [comment]
路線情報(API: odpt:Railway)
	路線名(半蔵門線)
	路線会社(odpt.Operator:TokyoMetro)
	路線ID(odpt.Railway:TokyoMetro.Hanzomon)
	到着駅(odpt.Station:TokyoMetro.Hanzomon.Kudanshita)
	到着駅番号(odpt:index)

**Comment by sakuyuki87** [comment]
@Haruyuki-Kobayashi 
佐野さんのテーブルに合わせる形だと、追加項目はodptを付けてもらえると嬉しいです。

**Comment by sakuyuki87** [comment]
@Haruyuki-Kobayashi 
odptIndexは数字が入るので、stringではなくIntergerでお願いします。

**Comment by Haruyuki-Kobayashi** [comment]
@sakuyuki87 コメント頂いた点を修正しました
