### ISSUE TITLE
押上駅対応

### ISSUE THREAD

**Issue by sakuyuki87** [odpt2018/sapj-opd-trainschedulebot-node#30]
現在、都営以外の押上駅は、<スカイツリー前>と入っている。
入力値に対応できないので、押上駅も追加する必要あり。
重要度:高

**Comment by Haruyuki-Kobayashi** [comment]
Stationのテーブルに正しい駅名かどうか判断するフラグを追加（基本は全部１）し、押上、麹町のようなゆらぎが発生する駅にはStation tableにレコードを追加。

取得するSQLは現在TOP1を取るようになっているので、そのフラグをチェックするように改修(where 句追加）
改修箇所メモ↓
//終着駅の行先日本語名を取得

**Comment by Haruyuki-Kobayashi** [comment]
京成線、半蔵門線、スカイツリーラインについて、Station tableに押上駅でレコードを追加しました
