### ISSUE TITLE
駅情報テーブルデータ投入

### ISSUE THREAD

**Issue by sakuyuki87** [odpt2018/sapj-opd-trainschedulebot-node#6]
駅情報テーブルデータの投入
とりあえずは、APIから落としたデータをマニュアル更新でOK
重要度:高

**Comment by Haruyuki-Kobayashi** [comment]
APIから落としたデータをExcelにして、CFのHANAのテーブルにデータを投入しました。

**Comment by sakuyuki87** [comment]
APIの制限により1000件しかデータが入っていない

**Comment by Haruyuki-Kobayashi** [comment]
データダンプAPIを利用 （一括でとれそう）or　データ取得APIで( operetorを指定して都度テーブルにデータ投入)
