### ISSUE TITLE
方面情報テーブルデータ投入

### ISSUE THREAD

**Issue by sakuyuki87** [odpt2018/sapj-opd-trainschedulebot-node#8]
方面情報テーブルデータの投入
まずは、APIから取得したデータをマニュアル登録でOK

方面を判別するための、昇順・降順フラグ(0 / 1)は、どこかでメンテナンスが必要

**Comment by Haruyuki-Kobayashi** [comment]
APIから落としたデータをExcelにして、CFのHANAのテーブルにデータを投入しました。
現時点ではメトロの情報のみ入っています。
